apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-ssd-path
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rancher.io/local-path
parameters:
  nodePath: /opt/minio-ssd-storage # ✅ 노드의 어떤 경로에 만들지 설정. 미리 설치 할 노드에 디렉토리 만들어 놓는다 
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false